import { useState, useEffect } from 'react'
import './App.css'

// ============ SLIDESHOW CONFIGURATION ============
const SLIDESHOW_CONFIG = {
  // Auto-play interval in milliseconds (1000 = 1 second)
  interval: 2000,

  // Start with auto-play enabled
  autoPlayOnLoad: false,

  // Sort images alphabetically by caption
  sortAlphabetically: true
}
// =================================================

interface CarouselImage {
  src: string
  alt: string
  caption: string
}

// Convert filename to readable caption (e.g., "linux-commands.jpg" -> "Linux Commands")
function filenameToCaption(filename: string): string {
  return filename
    .replace(/\.(jpg|jpeg|png|gif|webp)$/i, '')
    .split(/[-_]/)
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ')
}

function App() {
  const [images, setImages] = useState<CarouselImage[]>([])
  const [currentIndex, setCurrentIndex] = useState(0)
  const [isAutoPlaying, setIsAutoPlaying] = useState(SLIDESHOW_CONFIG.autoPlayOnLoad)
  const [isLightboxOpen, setIsLightboxOpen] = useState(false)

  // Load image list from manifest (generated by Vite plugin)
  useEffect(() => {
    fetch('/images/manifest.json')
      .then(res => res.json())
      .then((files: string[]) => {
        const loaded = files.map(file => ({
          src: `/images/${file}`,
          alt: filenameToCaption(file),
          caption: filenameToCaption(file)
        }))
        setImages(SLIDESHOW_CONFIG.sortAlphabetically
          ? loaded.sort((a, b) => a.caption.localeCompare(b.caption))
          : loaded
        )
      })
      .catch(() => setImages([]))
  }, [])

  useEffect(() => {
    if (!isAutoPlaying || images.length === 0) return
    const interval = setInterval(() => {
      setCurrentIndex((prev) => (prev + 1) % images.length)
    }, SLIDESHOW_CONFIG.interval)
    return () => clearInterval(interval)
  }, [isAutoPlaying, images.length])

  // Handle ESC key to close lightbox
  useEffect(() => {
    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && isLightboxOpen) setIsLightboxOpen(false)
    }
    window.addEventListener('keydown', handleEscape)
    return () => window.removeEventListener('keydown', handleEscape)
  }, [isLightboxOpen])

  // Prevent body scroll when lightbox is open
  useEffect(() => {
    document.body.style.overflow = isLightboxOpen ? 'hidden' : 'unset'
    return () => { document.body.style.overflow = 'unset' }
  }, [isLightboxOpen])

  const goToSlide = (index: number) => {
    setCurrentIndex(index)
    setIsAutoPlaying(false)
  }

  const goToPrevious = () => {
    setCurrentIndex((prev) => prev === 0 ? images.length - 1 : prev - 1)
    setIsAutoPlaying(false)
  }

  const goToNext = () => {
    setCurrentIndex((prev) => (prev + 1) % images.length)
    setIsAutoPlaying(false)
  }

  // Show message if no images found
  if (images.length === 0) {
    return (
      <div className="app-container">
        <div className="page-title">
          <h1>Carousel</h1>
        </div>
        <div className="content">
          <section className="info-section">
            <h2>No Images Found</h2>
            <p>
              Add image files (.jpg, .jpeg, .png, .gif, .webp) to the <code>public/images/</code> folder
              to see them in the carousel.
            </p>
          </section>
        </div>
      </div>
    )
  }

  return (
    <div className="app-container">
      <div className="page-title">
        <h1>Carousel</h1>
        <span className="image-counter">{currentIndex + 1} / {images.length}</span>
      </div>

      <div className="carousel-card">
        <div
          className="carousel-stage"
          onClick={() => { setIsLightboxOpen(true); setIsAutoPlaying(false) }}
          style={{ cursor: 'pointer' }}
        >
          <img
            src={images[currentIndex].src}
            alt={images[currentIndex].alt}
            className="carousel-image"
          />
          <div className="carousel-caption">
            {images[currentIndex].caption}
          </div>
        </div>

        <div className="carousel-bar">
          <button className="nav-btn" onClick={goToPrevious} aria-label="Previous image">‹</button>
          <div className="carousel-dots">
            {images.map((_, index) => (
              <button
                key={index}
                className={`dot ${index === currentIndex ? 'active' : ''}`}
                onClick={() => goToSlide(index)}
                aria-label={`Go to image ${index + 1}`}
              />
            ))}
          </div>
          <button className="play-btn" onClick={() => setIsAutoPlaying(!isAutoPlaying)}>
            {isAutoPlaying ? 'Pause' : 'Play'}
          </button>
          <button className="nav-btn" onClick={goToNext} aria-label="Next image">›</button>
        </div>
      </div>

      {/* Lightbox Modal */}
      {isLightboxOpen && (
        <div className="lightbox-overlay" onClick={() => setIsLightboxOpen(false)}>
          <button
            className="lightbox-close"
            onClick={() => setIsLightboxOpen(false)}
            aria-label="Close lightbox"
          >
            ×
          </button>
          <div className="lightbox-content" onClick={(e) => e.stopPropagation()}>
            <img
              src={images[currentIndex].src}
              alt={images[currentIndex].alt}
              className="lightbox-image"
            />
            <div className="lightbox-caption">
              {images[currentIndex].caption}
            </div>
          </div>
          <button
            className="lightbox-nav lightbox-prev"
            onClick={(e) => { e.stopPropagation(); goToPrevious() }}
            aria-label="Previous image"
          >
            ‹
          </button>
          <button
            className="lightbox-nav lightbox-next"
            onClick={(e) => { e.stopPropagation(); goToNext() }}
            aria-label="Next image"
          >
            ›
          </button>
        </div>
      )}
    </div>
  )
}

export default App
